name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run cypress:run
      - name: Archive test artifacts
        if: failure() # This will run only if the previous step fails
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
          